# server port : 9080
server:
  port: 9080

spring:
  application:
    name: demo80

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  thymeleaf:
    cache: false

  # Database Setting(datasource)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springgroup
    username: root
    password: 1234

  # JPA Setting
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update # create, update, none, create-drop, (배포)validate...
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  # user Password Setting(사용자 로그인 정보 설정)
  security:
    user:
      name: admin@green.com
      password: 1234




# Log information Setting
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

